### ISSUE TITLE
Code in sync.thread.js was not executed

### ISSUE THREAD

**Issue by feiyuntao** [backmeupplz/react-native-ios-threading-example#1]
Hi,  I saw your question on realm.js and was happy to find out that we are working on the same issue:  try to sync realm db in an another thread.  And I am struggling on that. 

I used your way here,  created syncThreadBridge with the bundelURL pointing to sync.thread.  But I cannot see  sync.thread.js 's reactotron.warn's output in Ractotron.  But can see the Reactotron's output from App.tsx.   I got the feeling the the code in sync.thread.js was not called.   What did I do wrong ? 

Thank you and I'd really appreciate your help.  If you are still working on that, it would be nice that we could have a discussion.  By the way, did you succeed in reading and writing realm in another thread ?

**Comment by backmeupplz** [comment]
We switched to wmdb and are happier than ever :) it's fast, lightweight and has built-in sync protocol

**Comment by feiyuntao** [comment]
Thank you for your reply.  I am afraid my company won’t accept switching
database, will still struggle doing this.


Really appropriate your reply.
